Make ~TException() virtual
apache/thrift pull request #2281
Opened 2020-11-19 10:49 UTC by emmenlau

This is a trivial change. It makes the destructor for the class `TException` virtual because its a base class for other exceptions. Base classes generally should have virtual destructors (or am I missing something very specific to this use case here?).

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [x] Did you squash your changes to a single commit?  (not required, but preferred)
- [x] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [x] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

2020-11-19 14:22 UTC, ulidtko requested changes
> Base classes generally should have virtual destructors

... whenever you're using runtime polymorphism — not in general.

An example would be:
```cpp
  TApplicationException* specific_derived_instance = [...];
  TException* upcasted_ptr = specific_derived_instance;
  delete upcasted_ptr;
```
For this code to work correctly, yes, `TException` dtor must be virtual.

If such usage isn't the case — then the extra cost of making *the whole class* virtual (which entails vtable creation and associated runtime lookups) may not be justified.

Put another way: if the class in question *has already* virtual methods -- you pay nothing, may as well slap that `virtual` onto the dtor and forget about it. If the class isn't virtual yet -- you pay the cost and need to consider if that's really needed.

... Does this solve a specific problem you have? Just asking.

2020-11-19 14:34 UTC, emmenlau commented
> > Base classes generally should have virtual destructors
> 
> ... whenever you're using runtime polymorphism — not in general.
> 
> For this code to work correctly, yes, `TException` dtor must be virtual.
> 
> ... Does this solve a specific problem you have? Just asking.

No, it was found only by chance because we have some exceptions that inherit from exceptions that inherit from `TException`. The static analyzer warned that the base class was not virtual and resources may be leaked.

2020-11-19 14:36 UTC, emmenlau commented
... and thanks for the nice review! You are perfectly correct that virtualization comes at a cost and is not required in all scenarios.

2020-11-19 14:39 UTC, ulidtko approved these changes
Oh well, `std::exception` is already virtual class and [has virtual dtor](https://en.cppreference.com/w/cpp/error/exception/~exception).

So this one should be marked as such too. LGTM

2020-11-25 11:01 UTC, emmenlau commented
The Travis errors seem to be unrelated, so this should be good to go!

2020-12-03 22:02 UTC, closed without merging

2020-12-03 22:14 UTC, emmenlau commented
Thanks @Jens-G !