add ubuntu focal build
apache/thrift pull request #2528
Opened 2022-02-22 02:38 UTC by Jimexist

- [ ] Did you create an [Apache Jira](https://issues.apache.org/jira/projects/THRIFT/issues/) ticket?  (not required for trivial changes)
- [ ] If a ticket exists: Does your pull request title follow the pattern "THRIFT-NNNN: describe my issue"?
- [ ] Did you squash your changes to a single commit?  (not required, but preferred)
- [ ] Did you do your best to avoid breaking changes?  If one was needed, did you label the Jira ticket with "Breaking-Change"?
- [ ] If your change does not involve any code, include `[skip ci]` anywhere in the commit message to free up build resources.

2022-02-26 12:11 UTC, Jens-G commented
```
The following packages have unmet dependencies:
 erlang : Depends: erlang-odbc
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y --no-install-recommends   `# Erlang dependencies`   erlang &&   wget https://s3.amazonaws.com/rebar3/rebar3 -O /usr/bin/rebar3 &&   chmod 755 /usr/bin/rebar3 &&   rebar3 --version' returned a non-zero code: 100
```

2022-03-06 11:51 UTC, Jens-G requested changes
See above

2022-03-07 20:54 UTC, Jens-G commented
Still broken. Also there is a possible conflict with #2541 ahead.

2022-03-08 15:26 UTC, Jimexist commented
> Still broken. Also there is a possible conflict with #2541 ahead.

yes so let me wait for that to merge first and then rebase & fix

2022-04-20 02:26 UTC, Jimexist commented
i think the latest CI fails because ubuntu:focal ships with openSSL 1.1.1f instead of 1.1.1 in e.g. xenial. This requires some test changes.

2022-04-20 02:28 UTC, Jimexist commented
cc @jeking3 the original author of `SecurityTest`. The failing tests is https://app.travis-ci.com/github/apache/thrift/jobs/567449611 - i am not sure if we need to drop some support or need to update the way parameters are constructed

2022-04-30 01:03 UTC, Jimexist commented
probably need to be done after:
- #2588 
is merged first

2022-09-12 08:01 UTC, Jimexist commented
@Jens-G do you think this can be merged? the refresh script did run correctly. the main errors are the same with `master`, i.e. Java errors, for which I'm trying to find time to fix.

2022-09-12 09:05 UTC, Jens-G commented
+1

2022-09-19 06:26 UTC, Jimexist commented
FYI @Jens-G @fishy or anyone who's interested, i'm merging this, given the current state of CI, i'd rather be iterating towards this (plus bionic) and move away from xenial.

2022-09-19 06:26 UTC, merged

2022-09-19 10:03 UTC, Jens-G commented
I would really appreciate if we could squash commits that belong together again before merging.

2022-09-19 11:59 UTC, Jimexist commented
> I would really appreciate if we could squash commits that belong together again before merging. And label it with the ticket number, btw.

thanks for the suggestion, i'd make sure to follow it next time.

2022-09-19 12:09 UTC, Jimexist commented
> I would really appreciate if we could squash commits that belong together again before merging. And label it with the ticket number, btw.

I just double checked that I indeed used GitHub's squash commit button, and the hash is f027deeaa8bf21769d83a35ac37ede21f035c0ad which is a single commit onto master. it only shows here in the pull request as a multi-commit pull request while in the master branch it's one. Did i miss anything?